apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-deploy-worker-squad2
  labels:
    name: stack-deploy-worker-squad2
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: stack-deploy-worker-squad2
  template:
    metadata:
      labels:
        name: stack-deploy-worker-squad2
    spec:
      subdomain: primary
      containers:
        - name: stack-deploy-worker-squad2
          image: d10s0vsky/sld-api:1.0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 300Mi
              cpu: 500m
          command: ["celery", "--app", "tasks.celery_worker", "worker", "--loglevel=info", "-c", "1", "-E", "-Q", "squad2"]
