name: Docker Image CI

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file sld-api-backend/Dockerfile --tag d10s0vsky/sld-api:$(date +%s)
